packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  uuid: ^11.1.1
allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - tsx@4.23.0
patchedDependencies:
  '@parry-gg/client@1.0.12': patches/@parry-gg__client@1.0.12.patch
