/**
 * V11 SEO: feature copy for the signed-out landing page's marketing
 * section. Names/wording match what the app itself calls these features
 * (see src/layouts/nav.ts and each feature's page) so search intent lines
 * up with what a visitor actually finds after signing in.
 */
export interface FeatureEntry {
  title: string;
  description: string;
}

export const featureEntries: FeatureEntry[] = [
  {
    title: 'GSP tracker & Elite Smash projection',
    description:
      'Log a quickplay match with the GSP shown on the results screen and Smash Tracker charts your climb per character. A community-reverse-engineered model of the hidden MMR behind GSP estimates your matches-to-Elite once you set your character’s Elite Smash threshold.',
  },
  {
    title: 'start.gg and parry.gg sync',
    description:
      'Link a start.gg or parry.gg account and Smash Tracker imports your tournament sets automatically — characters, stages, seeds, and placements — instead of typing every bracket match in by hand.',
  },
  {
    title: 'Matchup analytics & stage mastery',
    description:
      'A full matchup matrix with Wilson-confidence win rates across every character pairing, per-stage performance breakdowns, and a counterpick advisor that surfaces your best stage picks against a given opponent.',
  },
  {
    title: 'Scout any player',
    description:
      'Look up any start.gg or parry.gg player — by profile URL, slug, or player id — to see their characters, stages, and recent placements before you ever run into them in bracket.',
  },
  {
    title: 'AI scouting reports',
    description:
      'Turn a scouted opponent’s data into a written pre-bracket game plan generated by Claude. Free for allowlisted accounts; everyone else can buy a small credit pack.',
  },
  {
    title: 'Glicko-2 rating & friend leaderboards',
    description:
      'Every match feeds a Glicko-2 rating computed from your own history. Create or join a group with friends to compare rating, rating deviation, and games played on a shared leaderboard.',
  },
];
